<?php

use Illuminate\Database\Seeder;

class TablePermisosRolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(App\models\Permisos_rol::class)->create([
        		'id_menu'=>1,
        		'id_rol'=>1,
        		'id_depto'=>1,
        		'id_empresa'=>1,
        		'agregar'=>1,
        		'editar'=>1,
        		'eliminar'=>1,
        		'reportes'=>1,
        		'visible'=>1
        	]); 

        factory(App\models\Permisos_rol::class)->create([
        		'id_menu'=>6,
        		'id_rol'=>1,
        		'id_depto'=>1,
        		'id_empresa'=>1,
        		'agregar'=>1,
        		'editar'=>1,
        		'eliminar'=>1,
        		'reportes'=>1,
        		'visible'=>1
        	]); 

        factory(App\models\Permisos_rol::class)->create([
        		'id_menu'=>7,
        		'id_rol'=>1,
        		'id_depto'=>1,
        		'id_empresa'=>1,
        		'agregar'=>1,
        		'editar'=>1,
        		'eliminar'=>1,
        		'reportes'=>1,
        		'visible'=>1
        	]); 

        factory(App\models\Permisos_rol::class)->create([
        		'id_menu'=>8,
        		'id_rol'=>1,
        		'id_depto'=>1,
        		'id_empresa'=>1,
        		'agregar'=>1,
        		'editar'=>1,
        		'eliminar'=>1,
        		'reportes'=>1,
        		'visible'=>1
        	]); 

        factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>2,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

         factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>3,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>4,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>5,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>9,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>19,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>20,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);
		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>21,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>22,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>23,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>24,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>25,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>26,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>27,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>28,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>29,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);

		factory(App\models\Permisos_rol::class)->create([
			'id_menu'=>30,
			'id_rol'=>1,
			'id_depto'=>1,
			'id_empresa'=>1,
			'agregar'=>1,
			'editar'=>1,
			'eliminar'=>1,
			'reportes'=>1,
			'visible'=>1
		]);


		factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>10,
                'id_rol'=>7,
                'id_depto'=>3,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 
          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>11,
                'id_rol'=>7,
                'id_depto'=>3,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 
          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>12,
                'id_rol'=>7,
                'id_depto'=>3,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 
          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>13,
                'id_rol'=>7,
                'id_depto'=>3,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>9,
                'id_rol'=>28,
                'id_depto'=>9,
                'id_empresa'=>2,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

          factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>14,
                'id_rol'=>29,
                'id_depto'=>9,
                'id_empresa'=>2,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 

           factory(App\models\Permisos_rol::class)->create([
                'id_menu'=>15,
                'id_rol'=>1,
                'id_depto'=>1,
                'id_empresa'=>1,
                'agregar'=>1,
                'editar'=>1,
                'eliminar'=>1,
                'reportes'=>1,
                'visible'=>1
            ]); 
    }
}
